### ISSUE TITLE
Error Message: ??? with OTRS 5

### ISSUE THREAD

**Issue by Newbiez** [reneeb/otrs-ArticleCopyMoveDelete#3]
after installation i get this error with OTRS 5

Backend ERROR: OTRS-CGI-10 Perl: 5.12.3 OS: linux Time: Sun Aug 14 01:52:46 2016

 Message: ???

 RemoteAddress: 192.168.0.1
 RequestURI: /otrs/index.pl?Action=AgentArticleCopyMove;TicketID=4;ArticleID=8;

 Traceback (12014): 
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 196
   Module: /opt/otrs/bin/cgi-bin/index.pl Line: 40

**Comment by reneeb** [comment]
This should be fixed with version 5.0.1 that's on OPAR
